### ISSUE TITLE
Data Processors - styling

### ISSUE THREAD

**Issue by flashharry82** [lintol/lintol-frontend#81]
Magnifying glass needs aligned
![screen shot 2018-03-13 at 20 38 37](https://user-images.githubusercontent.com/954531/37368958-a6bac62c-26ff-11e8-9319-91f63e7e65c2.png)

Processor entry panel needs some right padding
![screen shot 2018-03-13 at 20 38 30](https://user-images.githubusercontent.com/954531/37368984-b5217b70-26ff-11e8-9836-de07f40ffe2c.png)

**Comment by martinnaughton** [comment]
fixed

**Comment by flashharry82** [comment]
Magnifying glass still not middle aligned.
![screen shot 2018-03-19 at 16 11 34](https://user-images.githubusercontent.com/954531/37607560-4029dd0e-2b90-11e8-829e-8e14ed42bc09.png)

**Comment by martinnaughton** [comment]
should be fixed now. what is your screen resolution?

**Comment by AndrewWalter** [comment]
this appears to be fixed
