### ISSUE TITLE
Reports - filter by profile

### ISSUE THREAD

**Issue by flashharry82** [lintol/lintol-frontend#82]
The filter by profile dropdown list doesn't seem to have all the profile options. There should be 5 but only 2 show.

![screen shot 2018-03-13 at 21 08 31](https://user-images.githubusercontent.com/954531/37369998-cb8df2d2-2702-11e8-8f05-f8c80ddf5e9b.png)

**Comment by martinnaughton** [comment]
fixed on scratch

**Comment by flashharry82** [comment]
still not showing all the profiles.
![screen shot 2018-03-19 at 16 13 04](https://user-images.githubusercontent.com/954531/37607634-791a9284-2b90-11e8-9dc7-03427138340b.png)

**Comment by flashharry82** [comment]
Also 'profile' text is being cut off.
![screen shot 2018-03-19 at 16 13 44](https://user-images.githubusercontent.com/954531/37607657-8aeadd48-2b90-11e8-800f-2ba0ce157bb7.png)

**Comment by martinnaughton** [comment]
it should show only the profiles that have reports. Not all profiles.

**Comment by martinnaughton** [comment]
will fix that cut off
